<?php
#DB_SYSTEM VARS

  	    $column_in_table[0]['name'] = "id";
  	    $column_in_table[0]['intable'] = true;
        $n = 1;
  	    $column_in_table[$n]['name'] = "fio";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "ФИО";
		$column_in_table[$n]['intable'] = true;
        $n++;
  	    $column_in_table[$n]['name'] = "role";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Должность";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "iin";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "ИИН";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "passport";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Паспорт";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "wherepass";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Кем и когда выдан";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "mobtel";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Мобильный";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "citytel";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Телефон";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "icq";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "ICQ";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "skype";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Skype";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "date";
   	    $column_in_table[$n]['input_type'] = "date";
  	    $column_in_table[$n]['fullname'] = "Дата Рождения";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "adres";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Адрес";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "email";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "E-mail";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "info";
   	    $column_in_table[$n]['input_type'] = "textarea";
  	    $column_in_table[$n]['fullname'] = "Информация";
		$column_in_table[$n]['intable'] = false;
        #$n++;
  	    #$column_in_table[$n]['name'] = "img";
  	    #$column_in_table[$n]['input_type'] = "image";
  	    #$column_in_table[$n]['img_path'] = "staff";
  	    #$column_in_table[$n]['fullname'] = "Картинка";
  	    #$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "login";
   	    $column_in_table[$n]['input_type'] = "text";
  	    $column_in_table[$n]['fullname'] = "Логин";
		$column_in_table[$n]['intable'] = false;
        $n++;
  	    $column_in_table[$n]['name'] = "password";
   	    $column_in_table[$n]['input_type'] = "password";
  	    $column_in_table[$n]['fullname'] = "Пароль";
		$column_in_table[$n]['intable'] = false;

        $n++;
		$column_in_table[$n]['name'] = "user_type";
   	    $column_in_table[$n]['input_type'] = "select";
  	    $column_in_table[$n]['fullname'] = "Доступ";
        $variants = array();
  	    $variants[0]['id'] = 1;$variants[0]['name']="Администратор";
  	    $variants[1]['id'] = 2;$variants[1]['name']="Директор";
  	    $variants[2]['id'] = 3;$variants[2]['name']="Главный Бухгалтер";
  	    $variants[3]['id'] = 4;$variants[3]['name']="Бухгалтер";
  	    $variants[4]['id'] = 5;$variants[4]['name']="Менеджер";
  	    $variants[5]['id'] = 6;$variants[5]['name']="Дизайнер";
  	    $variants[6]['id'] = 7;$variants[6]['name']="Производство";
  	    $variants[7]['id'] = 8;$variants[7]['name']="Доставка";

  	    $column_in_table[$n]['variants'] = $variants;
		$column_in_table[$n]['intable'] = false;

		$n++;
  	    $column_in_table[$n]['name'] = "mlinks";
   	    $column_in_table[$n]['input_type'] = "mlinks";
  	    $column_in_table[$n]['fullname'] = "Ссылки";
		$column_in_table[$n]['intable'] = false;
		$n++;
  	    $column_in_table[$n]['name'] = "mfiles";
   	    $column_in_table[$n]['input_type'] = "mfiles";
  	    $column_in_table[$n]['fullname'] = "Файлы";
		$column_in_table[$n]['intable'] = false;

        define("access_columns", "yes");
   	    $seo_columns = false;

?>