<?php
#DB_SYSTEM VARS

		$i=0;
  	    $column_in_table[$i]['name'] = "id";
  	    $column_in_table[$i]['intable'] = true;
        $i++;
   	    $column_in_table[$i]['name'] = "parent_id";
   	    $column_in_table[$i]['input_type'] = "parent_select_custom";
   	    $column_in_table[$i]['table'] = "project";
   	    $column_in_table[$i]['field'] = "stage_name";
   	    $column_in_table[$i]['rules'] = " ORDER BY parent_id, stage_name ASC";
  	    $column_in_table[$i]['fullname'] = "Родитель (Parent)";
		$column_in_table[$i]['intable'] = true;
        $defend_post['parent_id'] = C7_defend_post_fast ("parent_id");
        $i++;
  	    $column_in_table[$i]['name'] = "stage_name";
  	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Название этапа";
  	    $column_in_table[$i]['intable'] = true;
		$defend_post['stage_name'] = C7_defend_post_fast ("stage_name");
        $i++;
   	    $column_in_table[$i]['name'] = "student_cost";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Цена (Студент)";
		$column_in_table[$i]['intable'] = true;
		$defend_post['student_cost'] = C7_defend_post_fast ("student_cost");
        $i++;
   	    $column_in_table[$i]['name'] = "student_workdays";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Дни (Студент)";
		$column_in_table[$i]['intable'] = true;
        $defend_post['student_workdays'] = C7_defend_post_fast ("student_workdays");
        $i++;
     	$column_in_table[$i]['name'] = "amateur_cost";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Цена (Аматор)";
		$column_in_table[$i]['intable'] = true;
		$defend_post['amateur_cost'] = C7_defend_post_fast ("amateur_cost");
        $i++;
   	    $column_in_table[$i]['name'] = "amateur_workdays";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Дни (Аматор)";
		$column_in_table[$i]['intable'] = true;
        $defend_post['amateur_workdays'] = C7_defend_post_fast ("amateur_workdays");
        $i++;
     	$column_in_table[$i]['name'] = "pro_cost";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Цена (Профи)";
		$column_in_table[$i]['intable'] = true;
		$defend_post['pro_cost'] = C7_defend_post_fast ("pro_cost");
        $i++;
   	    $column_in_table[$i]['name'] = "pro_workdays";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Дни (Профи)";
		$column_in_table[$i]['intable'] = true;
        $defend_post['pro_workdays'] = C7_defend_post_fast ("pro_workdays");
        $i++;
   	    $column_in_table[$i]['name'] = "content";
   	    $column_in_table[$i]['input_type'] = "textarea";
  	    $column_in_table[$i]['fullname'] = "Описание(HTML)";
		$column_in_table[$i]['intable'] = false;
        $defend_post['content'] = C7_defend_filter ("2", $_POST['content']);
        $i++;
   	    $column_in_table[$i]['name'] = "img";
   	    $column_in_table[$i]['input_type'] = "image";
  	    $column_in_table[$i]['fullname'] = "Картинка";
		$column_in_table[$i]['intable'] = false;
        $defend_post['img'] = C7_defend_post_fast ("img");
        $i++;
   	    $column_in_table[$i]['name'] = "haschild";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Есть подразделы";
		$column_in_table[$i]['intable'] = false;
        $defend_post['haschild'] = C7_defend_post_fast ("haschild");
        $i++;
   	    $column_in_table[$i]['name'] = "short_text";
   	    $column_in_table[$i]['input_type'] = "textarea";
  	    $column_in_table[$i]['fullname'] = "Краткое описание";
		$column_in_table[$i]['intable'] = false;
        $defend_post['short_text'] = C7_defend_post_fast ("short_text");
        $i++;
		$column_in_table[$i]['name'] = "mandatory";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Обязательно";
		$column_in_table[$i]['intable'] = false;
        $defend_post['mandatory'] = C7_defend_post_fast ("mandatory");
        $i++;
		$column_in_table[$i]['name'] = "gallery";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Встроенная галерея";
		$column_in_table[$i]['intable'] = false;
        $defend_post['gallery'] = C7_defend_post_fast ("gallery");
        $i++;
		$column_in_table[$i]['name'] = "invisible";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Не показывать";
		$column_in_table[$i]['intable'] = false;
        $defend_post['invisible'] = C7_defend_post_fast ("invisible");
        $i++;
		$column_in_table[$i]['name'] = "fullimg";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Картинка в тексте";
		$column_in_table[$i]['intable'] = false;
        $defend_post['fullimg'] = C7_defend_post_fast ("fullimg");
        $i++;
		$column_in_table[$i]['name'] = "priority";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Приоритет";
		$column_in_table[$i]['intable'] = false;
        $defend_post['priority'] = C7_defend_post_fast ("priority");

   	    $seo_columns = false;
   	    define("access_columns", "no");
?>