<?php
#DB_SYSTEM VARS
        $i=0;
  	    $column_in_table[$i]['name'] = "id";
  	    $column_in_table[$i]['intable'] = true;
        $i++;
  	    $column_in_table[$i]['name'] = "page_name";
  	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Заголовок страницы";
  	    $column_in_table[$i]['intable'] = true;
		$defend_post['page_name'] = C7_defend_post_fast ("page_name");
        $i++;
   	    $column_in_table[$i]['name'] = "url";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "URL";
		$column_in_table[$i]['intable'] = true;
		$defend_post['url'] = C7_defend_post_fast ("url");
        $i++;
   	    $column_in_table[$i]['name'] = "parent_id";
   	    $column_in_table[$i]['input_type'] = "parent_select";
  	    $column_in_table[$i]['fullname'] = "Parent";
		$column_in_table[$i]['intable'] = true;
        $defend_post['parent_id'] = C7_defend_post_fast ("parent_id");
        $i++;
   	    $column_in_table[$i]['name'] = "content";
   	    $column_in_table[$i]['input_type'] = "textarea";
  	    $column_in_table[$i]['fullname'] = "Контент(HTML)";
		$column_in_table[$i]['intable'] = false;
        $defend_post['content'] = C7_defend_filter ("2", $_POST['content']);
        $i++;
   	    $column_in_table[$i]['name'] = "img";
   	    $column_in_table[$i]['input_type'] = "image";
  	    $column_in_table[$i]['fullname'] = "Картинка";
		$column_in_table[$i]['intable'] = true;
        $defend_post['img'] = C7_defend_post_fast ("img");
        $i++;
   	    $column_in_table[$i]['name'] = "haschild";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Есть подразделы";
		$column_in_table[$i]['intable'] = false;
        $defend_post['haschild'] = C7_defend_post_fast ("haschild");
        $i++;
   	    $column_in_table[$i]['name'] = "short_text";
   	    $column_in_table[$i]['input_type'] = "textarea";
  	    $column_in_table[$i]['fullname'] = "Краткое описание";
		$column_in_table[$i]['intable'] = false;
        $defend_post['short_text'] = C7_defend_filter ("2", $_POST['short_text']);
        $i++;
		$column_in_table[$i]['name'] = "inmain";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "На Главной";
		$column_in_table[$i]['intable'] = false;
        $defend_post['inmain'] = C7_defend_post_fast ("inmain");
        $i++;
        $column_in_table[$i]['name'] = "leadmaker";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "LeadMaker System";
		$column_in_table[$i]['intable'] = false;
        $defend_post['leadmaker'] = C7_defend_post_fast ("leadmaker");
        $i++;
		$column_in_table[$i]['name'] = "head_tags";
   	    $column_in_table[$i]['input_type'] = "textarea";
  	    $column_in_table[$i]['fullname'] = "&lt;head&gt;";
		$column_in_table[$i]['intable'] = false;
        $defend_post['head_tags'] = C7_defend_filter ("2", $_POST['head_tags']);
        $i++;
		$column_in_table[$i]['name'] = "gallery";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Встроенная галерея";
		$column_in_table[$i]['intable'] = false;
        $defend_post['gallery'] = C7_defend_post_fast ("gallery");
        $i++;
		$column_in_table[$i]['name'] = "invisible";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Не показывать";
		$column_in_table[$i]['intable'] = false;
        $defend_post['invisible'] = C7_defend_post_fast ("invisible");
        $i++;
		$column_in_table[$i]['name'] = "fullimg";
   	    $column_in_table[$i]['input_type'] = "checkbox";
  	    $column_in_table[$i]['fullname'] = "Картинка в тексте";
		$column_in_table[$i]['intable'] = false;
        $defend_post['fullimg'] = C7_defend_post_fast ("fullimg");
        $i++;
		$column_in_table[$i]['name'] = "priority";
   	    $column_in_table[$i]['input_type'] = "text";
  	    $column_in_table[$i]['fullname'] = "Приоритет";
		$column_in_table[$i]['intable'] = false;
        $defend_post['priority'] = C7_defend_post_fast ("priority");

   	    $seo_columns = true;
   	    define("access_columns", "yes");
?>