CREATE TABLE IF NOT EXISTS `catalog` (
  `id` bigint(12) NOT NULL AUTO_INCREMENT,
  `parent_id` bigint(20) NOT NULL,
  `visited` int(1) DEFAULT NULL,
  `inmenu` int(1) DEFAULT NULL,
  `rating` float DEFAULT NULL,
  `page_name` varchar(256) CHARACTER SET utf8 NOT NULL,
  `url` varchar(256) CHARACTER SET utf8 NOT NULL,
  `page_type` int(2) NOT NULL,
  `haschild` int(1) NOT NULL,
  `inmain` int(11) NOT NULL,
  `leadmaker` int(1) NOT NULL,
  `priority` int(7) NOT NULL,
  `gallery` int(1) NOT NULL,
  `invisible` int(1) NOT NULL,
  `fullimg` int(1) NOT NULL,
  `short_text` varchar(2048) COLLATE utf8_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `content` text CHARACTER SET utf8 NOT NULL,
  `head_tags` varchar(4096) COLLATE utf8_unicode_ci NOT NULL,
  `title` varchar(128) CHARACTER SET utf8 NOT NULL,
  `h1` varchar(128) CHARACTER SET utf8 NOT NULL,
  `description` varchar(256) CHARACTER SET utf8 NOT NULL,
  `keywords` varchar(1024) CHARACTER SET utf8 NOT NULL,
  `img` varchar(64) CHARACTER SET utf8 NOT NULL,
  `footer` varchar(256) CHARACTER SET utf8 NOT NULL,
  `creator` int(10) NOT NULL,
  `create_time` datetime NOT NULL,
  `updator` int(10) NOT NULL,
  `update_time` datetime NOT NULL,
  `user_read` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `user_write` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=19 ;
